---
version: '3.3'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Shubham@123
      MYSQL_DATABASE: attendance
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  java-backend:
    image: shubhamghongade/samstrackapi
    container_name: java-container
    ports:
      - "8081:8081"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/attendance?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Shubham@123
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
    networks:
      - app-network

  angular-app:
    image: shubhamghongade/samstrack
    container_name: angular-container
    ports:
      - "4200:4200"
    depends_on:
      - java-backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
...