FROM openjdk:17
MAINTAINER Shubham Ghongade<shubhanghongade199@gmail.com>
EXPOSE 8081
COPY SAMSTRACK_API/target/SamsTrack-0.0.1-SNAPSHOT.jar /usr/app/
WORKDIR /usr/app/
CMD ["java", "-jar","SamsTrack-0.0.1-SNAPSHOT.jar"]
